pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://modmaven.dev/' }
        maven { url = 'https://fabricmc.forgecdn.net/' }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
}

rootProject.name = 'minecraft-ai-agent'
